#!/usr/bin/env python3
"""Lift the 7 sherpas from raj-sadan into ai-sherpa (RAJ-68).

What's lifted:
* manifest.toml — copied with two adjustments:
    - The `[invocation].command` field is rewritten from
      `python v2/sherpa/<name>/main.py` to `python -m ai_sherpa <name>`
      so it reflects the new CLI dispatcher.
* main.py — copied verbatim. The Python is not (yet) parameterized; v0.0.1
  sherpas still reference raj-sadan's filesystem layout. Full portability
  is a v0.2 follow-up.
* Auxiliary files (component-index.toml, requirements.txt, etc.) — copied verbatim.
* _scaffold/ — copied wholesale; this is the template the CLI's `scaffold`
  command uses to generate new sherpas.

Per-sherpa README.md is generated by tools/build_readmes.py.
"""

from __future__ import annotations

import argparse
import re
import shutil
import sys
from pathlib import Path

REPO_ROOT = Path(__file__).resolve().parent.parent
PACKAGE_DIR = REPO_ROOT / "ai_sherpa"

SHERPAS = [
    "boot",
    "exit",
    "scrum",
    "design",
    "nextcloud",
    "crawler",
    "_scaffold",
]


def _rewrite_manifest_command(text: str, sherpa_name: str) -> str:
    """Rewrite `[invocation].command` to use the new CLI dispatcher.

    Old: command = "python v2/sherpa/<name>/main.py"
    New: command = "python -m ai_sherpa <name>"
    """
    pattern = re.compile(r'(command\s*=\s*)"[^"]*"')
    real_name = sherpa_name.lstrip("_")  # _scaffold runs via the scaffold subcommand
    if sherpa_name == "_scaffold":
        replacement = r'\1"python -m ai_sherpa scaffold <new-name>"'
    else:
        replacement = rf'\1"python -m ai_sherpa {real_name}"'
    return pattern.sub(replacement, text, count=1)


def lift_sherpa(source: Path, name: str) -> list[Path]:
    src_dir = source / "sherpa" / name
    if not src_dir.is_dir():
        print(f"  SKIP missing source: {src_dir}", file=sys.stderr)
        return []

    target_dir = PACKAGE_DIR / name
    target_dir.mkdir(parents=True, exist_ok=True)
    written: list[Path] = []

    for src in sorted(src_dir.iterdir()):
        if not src.is_file():
            continue
        target = target_dir / src.name
        if src.name == "manifest.toml":
            text = src.read_text(encoding="utf-8")
            text = _rewrite_manifest_command(text, name)
            target.write_text(text, encoding="utf-8", newline="\n")
        elif src.name in {"main.py", "__init__.py"}:
            shutil.copy2(src, target)
        else:
            shutil.copy2(src, target)
        written.append(target)
    return written


def main() -> int:
    p = argparse.ArgumentParser(description="Lift raj-sadan sherpas into ai-sherpa.")
    p.add_argument("--source", type=Path, default=Path("I:/raj_sadan"))
    p.add_argument("--clean", action="store_true", help="Wipe per-sherpa dirs first")
    args = p.parse_args()

    if not args.source.is_dir():
        print(f"error: source dir not found: {args.source}", file=sys.stderr)
        return 2

    if args.clean:
        for name in SHERPAS:
            d = PACKAGE_DIR / name
            if d.exists():
                shutil.rmtree(d)

    all_files: list[Path] = []
    for name in SHERPAS:
        print(f"lifting {name}")
        all_files.extend(lift_sherpa(args.source, name))

    # Make every sherpa dir a Python package by adding __init__.py if missing.
    for name in SHERPAS:
        init = PACKAGE_DIR / name / "__init__.py"
        if not init.exists() and (PACKAGE_DIR / name).is_dir():
            init.write_text(
                f'"""{name} sherpa — see manifest.toml for details."""\n',
                encoding="utf-8",
            )
            all_files.append(init)

    print(f"\nWrote {len(all_files)} files")
    for f in all_files:
        print(f"  {f.relative_to(REPO_ROOT)}")
    return 0


if __name__ == "__main__":
    raise SystemExit(main())
